group: edge
dist: jammy
virt: vm
os: linux

arch:
  - amd64

services:
  - docker

language: shell

# addons:
#   apt:
#     packages:
#       - docker-ce

env:
  - DIR=chrome-stable REPO=yukinying/chrome-headless-browser-stable TARGET=Chromium
  - DIR=chrome REPO=yukinying/chrome-headless-browser TARGET=Chrome
  - DIR=chrome-xl REPO=yukinying/chrome-headless-browser-xl TARGET=Chrome
  - DIR=chromedriver REPO=yukinying/chrome-headless-browser-selenium TARGET=Chrome

jobs:
  include:
  - arch: arm64-graviton2
    env: DIR=chrome-stable REPO=yukinying/chrome-headless-browser-stable TARGET=Chromium

before_install:
  # update libseccomp
  # - sudo apt-get update 
  # - sudo apt-get -y install libseccomp
  # # install latest docker
  # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  # - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  # - sudo apt-get update
  # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # collect data from previous image
  - export ARCH=${TRAVIS_CPU_ARCH/-graviton2/} # remove unnecessary architecture annotation.
  - export VERSION0=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - export VERSION0=${VERSION0:-NONE}
  # build 
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $REPO $DIR

script:
  - export VERSION1=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - echo "Version before build = $VERSION0"
  - echo "Version after build  = $VERSION1"
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$VERSION1
  - docker tag $REPO $REPO-$ARCH:latest
  - docker tag $REPO $REPO-$ARCH:$VERSION1
  - docker run --init -it --rm --name chrome --cap-add=SYS_ADMIN --entrypoint=/usr/bin/google-chrome $REPO:latest   --headless --disable-dev-shm-usage --disable-gpu --dump-dom http://info.cern.ch/hypertext/WWW/TheProject.html | grep "The World Wide Web project"
  - test -x $DIR/tests/test.sh && cd $DIR/tests && ./test.sh && cd ../..
  - ./push.sh

