sudo: required

services:
  - docker

language: go

go:
  - '1.5'

before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb 
  - docker build -t yukinying/chrome-headless-browser-docker .

