sudo: required
group: edge
dist: focal
virt: vm

arch:
  - amd64
  - arm64-graviton2

services:
  - docker

language: bash

env:
  - REPO=yukinying/chrome-headless-browser-stable DIR=chrome-stable TARGET=Chromium
#  - REPO=yukinying/chrome-headless-browser DIR=chrome TARGET=Chrome
#  - REPO=yukinying/chrome-headless-browser-xl DIR=chrome-xl TARGET=Chrome
#  - REPO=yukinying/chrome-headless-browser-selenium DIR=chromedriver TARGET=Chrome

before_install:
  - export VERSION0=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $REPO $DIR

script:
  - export VERSION1=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$VERSION1
  - docker run --init -it --rm --name chrome --cap-add=SYS_ADMIN --entrypoint=/usr/bin/google-chrome $REPO:latest   --headless --disable-dev-shm-usage --disable-gpu --dump-dom http://info.cern.ch/hypertext/WWW/TheProject.html
  - test -x $DIR/tests/test.sh && cd $DIR/tests && ./test.sh && cd ../..

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$VERSION0" != "$VERSION1" ]; then
    docker push $REPO:latest;
    docker push $REPO:$VERSION1;
    fi
