group: edge
dist: focal
virt: vm
os: linux

arch:
  - amd64

services:
  - docker

language: shell

env:
  - DIR=chrome-stable REPO=yukinying/chrome-headless-browser-stable TARGET=Chromium
  - DIR=chrome REPO=yukinying/chrome-headless-browser TARGET=Chrome
#  - DIR=chrome-xl REPO=yukinying/chrome-headless-browser-xl TARGET=Chrome
#  - DIR=chromedriver REPO=yukinying/chrome-headless-browser-selenium TARGET=Chrome

jobs:
  include:
  - arch: arm64-graviton2
    env: DIR=chrome-stable REPO=yukinying/chrome-headless-browser-stable TARGET=Chromium

before_install:
  - export VERSION0=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $REPO $DIR

script:
  - export VERSION1=`docker run --name chrome --rm --entrypoint=/usr/bin/google-chrome $REPO --version | grep -Po "(?<=$TARGET )[^ ]+"`
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$VERSION1
  - docker run --init -it --rm --name chrome --cap-add=SYS_ADMIN --entrypoint=/usr/bin/google-chrome $REPO:latest   --headless --disable-dev-shm-usage --disable-gpu --dump-dom http://info.cern.ch/hypertext/WWW/TheProject.html
  - test -x $DIR/tests/test.sh && cd $DIR/tests && ./test.sh && cd ../..

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$VERSION0" != "$VERSION1" ]; then
    docker push $REPO:latest;
    docker push $REPO:$VERSION1;
    fi
    #  - if [ "$TRAVIS_BRANCH" == "stable" ] && [ "$MULTIARCH" == "1" ]; then
    # docker push $REPO-$TRAVIS_CPU_ARCH:latest;
    # docker push $REPO-$TRAVIS_CPU_ARCH:$VERSION1;
    # fi
